language: ruby
rvm: 2.5.0
sudo: false
git:
  submodules: false
env:
  global:
    - secure: "ctR2TBzDCr2xX1bQc5XFxq+ZbVwei3iBA4KWO/U/VS88AltU1qvIarDOLufFI15p/OSZhh4lwuInXNrYfp1216fJaFrvO1Ve0dTsqXW70Ayx8y9bTo0PZ+y0XLvv+6bCZa+5XUWvce5JtLMqcOOnyX705lNOAI+8jLuRva+rYH0="
    - BUCKET=arch.wanko.cc
    - REGION=ap-northeast-1
    - TZ=Asia/Tokyo
before_script:
  - touch .env
script:
  - bundle exec middleman build
after_success:
  - bundle exec middleman s3_sync
branches:
  only:
    - master
