---
name: aur-eagletmt
package_key: C48DBD97
repo_key: C48DBD97
srcdest: sources
logdest: logs
pkgbuild: PKGBUILDs
builds:
  x86_64:
    chroot: ../x86_64-root
s3:
  bucket: arch.wanko.cc
  region: ap-northeast-1
